## NAME : HARII SARAVANAN A
## DEPARTMENT : ARTIFICIAL INTELLIGENCE AND DATA SCIENCE
## YEAR/SEMESTER/SECTION : II / III /  A

# Data Preprocessing Using Stock Price Dataset 

## Steps Required:
## 1.Getting the Dataset
## 2.Importing libraries
## 3.Importing Datasets
## 4.Finding Missing Data
## 5.Encoding Categorical Data
## 6.Splitting datasets Into Training and Testing Set
## 7.Feature Scaling

## 1.Getting Datasets

## Get the datasets for stock prrediction in kaggle and ucimlrepository

In [69]:
# stock prediction dataset with null values for preprocessing

## Importing Libraries

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing Datasets

In [71]:
data = pd.read_csv('Data.csv')
data

Date        Open        High         Low       Close   Adj_Close  \
0     2000/3/27    3.812500    4.156250    3.812500    4.125000         NaN   
1     2000/3/28    4.125000         NaN    4.000000    4.015625    4.015625   
2     2000/3/29    4.000000    4.031250    3.953125    4.000000    4.000000   
3     2000/3/30         NaN    4.000000         NaN    3.843750    3.843750   
4     2000/3/31    3.734375         NaN    3.390625    3.390625    3.390625   
...         ...         ...         ...         ...         ...         ...   
4387   2017/9/1  113.790001  114.099998  112.790001  113.309998  113.309998   
4388   2017/9/5  112.519997  113.529999  111.160004  111.870003  111.870003   
4389   2017/9/6  112.029999  112.489998  110.250000  112.230003  112.230003   
4390   2017/9/7  112.459999         NaN  112.000000  112.339996  112.339996   
4391   2017/9/8  112.300003  114.790001  112.010002  113.190002  113.190002   

         Volume  
0     3675600.0  
1     1077600.0  
2      437200.0  
3     1883600.0  
4     7931600.0  
...         ...  
4387   950000.0  
4388  1805200.0  
4389  2136700.0  
4390        NaN  
4391        NaN  

[4392 rows x 7 columns]

In [72]:
data.info()#in dataset have any null values or not

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4392 entries, 0 to 4391
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       4392 non-null   object 
 1   Open       3953 non-null   float64
 2   High       3959 non-null   float64
 3   Low        3924 non-null   float64
 4   Close      3960 non-null   float64
 5   Adj_Close  3945 non-null   float64
 6   Volume     3980 non-null   float64
dtypes: float64(6), object(1)
memory usage: 240.3+ KB


In [73]:
#describe means return description of data in dataframe

In [74]:
data.describe()

Open         High          Low        Close    Adj_Close  \
count  3953.000000  3959.000000  3924.000000  3960.000000  3945.000000   
mean     30.522811    30.830337    30.266694    30.544287    30.548548   
std      29.769267    30.167726    29.591556    29.914408    30.014424   
min       3.437500     3.390625     3.093750     3.250000     3.250000   
25%       8.745000     8.825000     8.608750     8.730000     8.650000   
50%      14.820000    14.995000    14.700000    14.765000    14.625000   
75%      42.480000    42.929998    42.167500    42.526251    42.490002   
max     121.080002   121.750000   120.169998   121.360001   121.360001   

             Volume  
count  3.980000e+03  
mean   1.891657e+06  
std    1.661660e+06  
min    1.904000e+05  
25%    1.087500e+06  
50%    1.537400e+06  
75%    2.184000e+06  
max    4.641260e+07

## Extracting the dependent and independent Variable

In [75]:
x = data.iloc[:,0:3].values

In [76]:
x

array([['2000/3/27', 3.8125, 4.15625],
       ['2000/3/28', 4.125, nan],
       ['2000/3/29', 4.0, 4.03125],
       ...,
       ['2017/9/6', 112.029999, 112.489998],
       ['2017/9/7', 112.459999, nan],
       ['2017/9/8', 112.300003, 114.790001]], dtype=object)

In [77]:
y = data['Close']

In [78]:
y

0         4.125000
1         4.015625
2         4.000000
3         3.843750
4         3.390625
           ...    
4387    113.309998
4388    111.870003
4389    112.230003
4390    112.339996
4391    113.190002
Name: Close, Length: 4392, dtype: float64

## Finding Missing Data

In [79]:
#filling missing data with null values 

In [80]:
from sklearn.impute import SimpleImputer

In [81]:
#using median value fill in null values from 1st to 2nd column
imputer  = SimpleImputer(missing_values = np.nan,strategy='median')
imputer.fit(x[:,1:3])
#replace missing data with calculate median value
x[:,1:3] = imputer.transform(x[:,1:3])

## Encoding Categorical Data

In [82]:
# We will convert date values into catgorical data.using labelencoder

In [83]:
# import labelencoder using sckit-learn library
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,0] = le.fit_transform(x[:,0])

## Splitting dataset into training and testing sets

In [84]:
#splitting into training and testing data

In [85]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=1)

In [86]:
#testsize means size of test data may be in 0.5,0.3,0.2 dividing ratio of training and testing sets

In [87]:
print(x_train)
print(x_test)

[[1607 10.9675 11.025]
 [1564 11.215 11.2875]
 [567 6.8525 6.895]
 ...
 [752 7.2625 7.2775]
 [3975 78.790001 79.779999]
 [305 5.3075 14.995]]
[[3827 74.894997 75.205002]
 [3109 42.110001 42.360001]
 [577 6.775 6.775]
 ...
 [3842 70.995003 72.934998]
 [2458 22.75 22.950001]
 [2318 15.2925 15.5175]]


In [88]:
print(y_train)
print(y_test)

1549    10.987500
1506    11.205000
509      6.765000
3290    32.084999
3949    80.394997
          ...    
2895    37.935001
2763    43.310001
905      7.270000
3980    78.839996
235      5.062500
Name: Close, Length: 2635, dtype: float64
3768     73.385002
3053     41.685001
518       6.702500
2772     42.740002
2500     24.195000
           ...    
4315    114.089996
1857     11.775000
3783     71.550003
2463     22.937500
2259     15.475000
Name: Close, Length: 1757, dtype: float64


## Feature Scaling

In [89]:
#feature scaling
# rescale values between -1 and 1

In [90]:
#standardscalar for independent or features variable
#technique standard independent variable in specific range

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,:] = sc.fit_transform(x_train[:,:])
x_test[:,:] = sc.fit_transform(x_test[:,:])

In [92]:
print("X_train:\n\n",x_train)
print("X_test:\n\n",x_test)

X_train:

 [[-0.4660504508059631 -0.6256605485316984 -0.6233593080840402]
 [-0.49989499357936346 -0.6170871925492674 -0.614378152019488]
 [-1.2846161364882054 -0.7682034166840371 -0.7646628301663266]
 ...
 [-1.1390058943235757 -0.75400108960203 -0.7515760027579793]
 [1.3977606489012964 1.723698823960369 1.7290192680573857]
 [-1.490831722688924 -0.8217219419076977 -0.48753001446014727]]
X_test:

 [[1.295196083860797 1.6294227956521974 1.5982717932055128]
 [0.7270912281837155 0.4695155837526536 0.4545549356950777]
 [-1.2763091820869954 -0.7806087869313502 -0.7845732201611421]
 ...
 [1.307064569703633 1.4914440944510456 1.5192265271872192]
 [0.21199894260463462 -0.21542592980685302 -0.22133313032378302]
 [0.10122640807149895 -0.4792663778197442 -0.48014501731879844]]


# Thank You